### ISSUE TITLE
Fix Unpinned-Dependencies on Apptainer Action

### ISSUE THREAD

**Issue by tylertitsworth** [intel/ai-containers#234]
Tracking issue for:
- [ ] https://github.com/intel/ai-containers/security/code-scanning/1643
- [ ] https://github.com/intel/ai-containers/security/code-scanning/1644
- [ ] https://github.com/intel/ai-containers/security/code-scanning/1645

**Comment by sramakintel** [comment]
issue addressed in https://github.com/intel/ai-containers/pull/235
