### ISSUE TITLE
ipex-xpu-jupyter in https://github.com/intel/ai-containers/blob/main/pytorch/Dockerfile is incorrectly checking for conda

### ISSUE THREAD

**Issue by jketreno** [intel/ai-containers#244]
### Describe the bug

While trying to add some additional functionality to a derived version of the ipex-xpu-jupyter container, attempting to access the shell results in bash complaining that conda does not exist:

```
docker run -it --rm \
    -p 8888:8888 \
    --net=host \
    --device /dev/dri \
    -v /dev/dri/by-path:/dev/dri/by-path \
    --ipc=host \
    intel/intel-extension-for-pytorch:2.1.20-xpu-pip-jupyter \
    /bin/bash
WARNING: Published ports are discarded when using host network mode
bash: conda: command not found
```

Conda is not installed in the intel-xpu-base layer, nor intel-xpu-jupyter layer. However, the Dockerfile layer for intel-xpu-jupyter is adding 'conda activate idp' regardless. This is due to this check in the Dockerfile:

```Dockerfile
RUN if [ ! -d "$(which conda)" ]; then \
    echo "conda activate idp" >> ~/.bashrc; \
    fi
```

That check is attempting to check if conda exists, and then add the `conda activate idp` to the .bashrc. 

However, `which` returns the path to the executable (if it is in the path) and not a file. The the '-d' check will fail if conda is installed (which returns file path) and if conda is not installed (which returns nothing, so no directory). The '!' inverts that failure to be success. The net result is the conda command will be added to ~/.bashrc regardless of whether conda exists or not.

A corrected line:

```bash
# If conda is in the path, activate idp environment
RUN if $(which conda >/dev/null); then \
    echo "conda activate idp" >> ~/.bashrc \
fi
```

The instructions are also telling the user to publish a port (-p) and use --net=host; you shouldn't need --net=host since you are publishing the internal port 8888 to the host port 8888.

### Error Logs

```Markdown
WARNING: Published ports are discarded when using host network mode
bash: conda: command not found
```

### Reproduction Instructions

```Markdown
docker run -it --rm \
    -p 8888:8888 \
    --net=host \
    --device /dev/dri \
    -v /dev/dri/by-path:/dev/dri/by-path \
    --ipc=host \
    intel/intel-extension-for-pytorch:2.1.20-xpu-pip-jupyter \
    /bin/bash
```

### Affected Subfolder

- [ ] classical-ml
- [ ] enterprise
- [ ] preset
- [ ] python
- [X] pytorch
- [ ] tensorflow
- [ ] test-runner
- [ ] workflows

### Versions

```Markdown
intel/intel-extension-for-pytorch:2.1.20-xpu-pip-jupyter
```

**Comment by sramakintel** [comment]
@jketreno Thanks for reaching out. 

Our `pip` based images like the one you tried do not contain `conda` environments. What you want is image with tag `idp` or intel distribution of python that has default `conda` support. Please try `docker pull intel/intel-extension-for-pytorch:2.1.20-xpu-idp-jupyter` instead. 

Here is a screenshot of conda
after i did `docker run -it --device /dev/dri intel/intel-extension-for-pytorch:2.1.20-xpu-idp-jupyter /bin/bash`

![image](https://github.com/user-attachments/assets/3f9bac7d-a20b-438f-9d9e-13c50dd0a867)

**Comment by jketreno** [comment]
> @jketreno Thanks for reaching out.
> 
> Our `pip` based images like the one you tried do not contain `conda` environments. What you want is image with tag `idp` or intel distribution of python that has default `conda` support. Please try `docker pull intel/intel-extension-for-pytorch:2.1.20-xpu-idp-jupyter` instead.

It is fine that it doesn't have conda in it -- the problem is the [Dockerfile](https://github.com/intel/ai-containers/blob/main/pytorch/Dockerfile#L207) you are using and publishing as an image is incorrectly checking to see if conda is installed in the container and then doing the wrong thing:

![image](https://github.com/user-attachments/assets/2456eed5-08af-435a-a59f-506d3f36e5af)

**Comment by sramakintel** [comment]
@jketreno.  Got it! The issue has been addressed and merged to the main branch.  This fix will be reflected in a future container release to docker hub.
