### ISSUE TITLE
Tensorflow build with AVX512?

### ISSUE THREAD

**Issue by Jille** [intel/ai-containers#272]
### Description

Is there a version of this image with that uses AVX512 available?

https://hub.docker.com/r/intel/intel-optimized-tensorflow-avx512 seems unmaintained, so I'm hoping these images can fill that gap :)

```
tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

### Describe the solution you'd like

Duplicate all tags of https://hub.docker.com/r/intel/intel-extension-for-tensorflow to have a version that uses AVX512.

**Comment by tylertitsworth** [comment]
Hi @Jille, AVX512 instructions require the package to be built from source. This [source](https://pypi.org/project/intel-tensorflow-avx512/)'s last version was `2.14.0`, and the last container we published with AVX512 was `2.13.0`.

We can publish the `2.14.0` image if it fits your use-case, however we know that AVX512 support will not continue on intel extension for Tensorflow, and as such won't be supporting the container product unless there is enough demand for it.
